version: "3.9"
services:
  hospital_location_backend:
    build: .
    image: skinmatch/hospital-backend:latest
    environment:
      - PORT=8002
      - LOG_LEVEL=info
    ports:
      - "8002:8002"
    restart: unless-stopped

